[package]
name = "Processor"
version = "13.0.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
serenity = "0.12.2"
reqwest = "0.11"
tokio = { version = "1.40.0", features = ["full"] }
serde_json = "1.0.137"
